import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Footer from "./ui/Footer";
import Nav from "./ui/Nav";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={plusJakartaSans.className} lang="es">
      <body className="d-flex flex-column">
        <main className="flex-shrink-0 ">
          <Nav />

          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
